### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AlexiOS21bruh** [IsaacMarovitz/Whisky#116] opened 2023-06-16 19:52 UTC
### Description

Cannot install Epic Games Launcher. Whenever i try to install it, even after downloading all the redistributables needed and the framework v 4.8. i can't open EGL. It always says failed to autoupdate.

### Steps to reproduce

Just try to install EGL on a win 10 bottle

### Expected behaviour

I expected the Launcher to be able to open after all the redistributables.

### Logs

```bash
how exactly? sorry
```

### What version of Whisky are you using?

pre-0.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-06-16 20:57
Duplicate of #101

**Closed by IsaacMarovitz** 2023-06-16 20:57 UTC
Labels: bug
