### ISSUE TITLE
[Bug]: M1 Max returns  "No GPUs found! A GPU is required to play Diablo IV. This might occur if you are currently installing GPU drivers."

### ISSUE THREAD

**Issue by zhtianyou** [IsaacMarovitz/Whisky#121] opened 2023-06-17 01:22 UTC
### Description

I installed Battle.net.exe, and finished downloading Diablo IV. Clicking the Play button returns "No GPUs found! A GPU is required to play Diablo IV. This might occur if you are currently installing GPU drivers."

Could anyone tell me how to fix this issue? How can I install the driver and run the game? I really appreciate it if you guys can show me some codes to fix it.

Thanks!

### Steps to reproduce

regedit windows version to 19042

start diablo 4 in Battle.net

### Expected behaviour

start game

### Logs

```bash
Whisky Version: pre-0.3.0
Date: 2023/6/17, 9:12:44
macOS Version: Version 14.0 (Build 23A5257q)
Bottle Name: D4
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/youwin/D4

Arguments: start /unix /Users/youwin/D4/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe 

Launched Wine (33229)
01b8: thread_get_state failed on Apple Silicon - faking zero debug registers
0214: thread_get_state failed on Apple Silicon - faking zero debug registers
0278: thread_get_state failed on Apple Silicon - faking zero debug registers
0160: thread_get_state failed on Apple Silicon - faking zero debug registers
02cc: thread_get_state failed on Apple Silicon - faking zero debug registers
02f8: thread_get_state failed on Apple Silicon - faking zero debug registers
0328: thread_get_state failed on Apple Silicon - faking zero debug registers
04e0: thread_get_state failed on Apple Silicon - faking zero debug registers
04f0: thread_get_state failed on Apple Silicon - faking zero debug registers
0550:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0160: thread_get_state failed on Apple Silicon - faking zero debug registers
06a8: thread_get_state failed on Apple Silicon - faking zero debug registers
06e8: thread_get_state failed on Apple Silicon - faking zero debug registers
0734: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

pre-0.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mangofever** [comment] 2023-06-17 09:48
+1

**Comment by kode54** [comment] 2023-06-17 10:31
Same problem with System Shock Remake, it detects no graphics hardware. GPT works just fine.

**Comment by IsaacMarovitz** [comment] 2023-06-17 10:58
Duplicate of #124

**Closed by IsaacMarovitz** 2023-06-17 10:58 UTC
Labels: bug

**Comment by itskando** [comment] 2023-07-03 14:34
+1

**Comment by millzanz** [comment] 2023-07-03 16:22
Same here.Sent from my iPhoneOn Jul 3, 2023, at 7:34 AM, Kando ***@***.***> wrote:﻿
+1
