### ISSUE TITLE
[Feature]: Create shortcuts to launch exes with whisky 

### ISSUE THREAD

**Issue by ArmasF31** [IsaacMarovitz/Whisky#150] opened 2023-06-21 05:55 UTC
### Is your feature request related to a problem?

Not a problem, more of an annoyance. If you want to open an already installed program, you need to either click the shortcut (if detected) and then press start, or search for the exe in the file system.

### Describe the solution you'd like

I'm unsure how complicated this is to do, but I'd like the option to add an app as a shortcut to the launchpad so you can open it with one click. Obviously whisky will still need to open, but for the end user it would be one click.

### Anything else?

Let me know if you need anything.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-06-21 11:05
One-click open added in next release, partial duplicate of #42

**Closed by IsaacMarovitz** 2023-06-21 11:05 UTC
Labels: enhancement

**Comment by Squid4572** [comment] 2023-09-01 18:34
this is not done. there is still no way to create launchers for whisky programs.

**Comment by Squid4572** [comment] 2023-09-01 18:35
@IsaacMarovitz please implement this as it's very important for certain workflows.
