### ISSUE TITLE
Battl.net Update and Restart Issue[Bug]: 

### ISSUE THREAD

**Issue by Mrblutziii** [IsaacMarovitz/Whisky#289] opened 2023-08-06 22:30 UTC
### Description

When starting up Battle.net launcher the indicator for an "update and restart" will appear in top left corner. When I press it the app closes, but never returns. I have to force quit and restart the launcher. But it still requires and update.

### Steps to reproduce

Launch Battle.net

Hit "Update and Restart"

Force Quit Battle.net when it does not open up again

Restart Battle.net

### Expected behaviour

Battle.net Launcher to update and restart

### Logs

```bash
Uncertain (I am not a developer)
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-08-08 13:22
Duplicate of #224

**Closed by IsaacMarovitz** 2023-08-08 13:22 UTC
Labels: bug
