### ISSUE TITLE
Make Windows 10 - Build 19045.2965 Default (Or something newer than 1906)

### ISSUE THREAD

**Issue by millzanz** [IsaacMarovitz/Whisky#46] opened 2023-06-08 18:15 UTC
Hey there,

Just was wondering if the windows build of 10 that is getting reported could be updated?  Instead of manually going in to change it to get some games working.

**Comment by Moeinich** [comment] 2023-06-08 18:36
How do you manually change it? I hear that's the fix for battlenet launcher?

**Comment by IsaacMarovitz** [comment] 2023-06-08 19:03
Duplicate of #18

**Closed by IsaacMarovitz** 2023-06-08 19:03 UTC

**Comment by millzanz** [comment] 2023-06-09 19:56
You can change it by changing system.reg in wine ‘current version’. Then that is what is reported to the systemSent from my iPhoneOn Jun 8, 2023, at 12:04 PM, Isaac Marovitz ***@***.***> wrote:﻿
Duplicate of #18
