### ISSUE TITLE
[Feature]: Install instructions

### ISSUE THREAD

**Issue by richstokes** [IsaacMarovitz/Whisky#65] opened 2023-06-09 18:51 UTC
### Is your feature request related to a problem?

Yes, theres nothing in the readme that says how to download and install whisky

### Describe the solution you'd like

Links to download / any pertinant info in the readme

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by ares-cg** [comment] 2023-06-09 19:52
+1

**Comment by Marsgames** [comment] 2023-06-09 20:50
This one is a duplicate of #55
(+ #55 explain kinda explain hot to do it, "go to the '[Releases](https://github.com/IsaacMarovitz/Whisky/releases)' tab and then expanding the 'Assets'" --> [download Whisky.zip](https://github.com/IsaacMarovitz/Whisky/releases/download/pre-0.2.2/Whisky.zip) --> have fun)

**Comment by IsaacMarovitz** [comment] 2023-06-14 13:55
Added Wiki

**Closed by IsaacMarovitz** 2023-06-14 13:55 UTC
Labels: enhancement
