### ISSUE TITLE
[Bug]: Trackmania 2020 Won't Let Me Load Into a Track

### ISSUE THREAD

**Issue by cirava** [IsaacMarovitz/Whisky#260] opened 2023-07-23 00:33 UTC
### Description

When I launch TM2020 from Steam, it allows me to get into the menus perfectly fine. Everything is where it should be, 3D models even display correctly. However, as soon as I attempt to load into a track, the game freezes on the loading screen, and Wine gives me an error telling me the application encountered an error and it had to stop.

I am on a M1 Macbook Air

### Steps to reproduce

1. Open Steam
2. Download TM2020
3. Launch TM2020
4. Attempt to load into a track

### Expected behaviour

I would expect the game to load into the track as normal.

### Logs

```bash
Whisky Version: 1.0.1
Date: 7/22/2023, 8:15:10 PM
macOS Version: Version 14.0 (Build 23A5286i)
Bottle Name: trackmania
Wine Version: 7.7.0
Wine Binary Version: 4
Windows Version: win10
Bottle URL: /Volumes/transDriveA/2B11FC47-AB78-4422-AAAF-B9867DC03377

Arguments: start C:\Program Files (x86)\Steam\steam.exe 

Environment:
{
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
}

Launched Wine (51680)
00a0:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\pf2ajcyb": c0000142
0188: thread_get_state failed on Apple Silicon - faking zero debug registers

(wine:51730): GStreamer-CRITICAL **: 20:15:21.496: _gst_util_uint64_scale: assertion 'denom != 0' failed
00dc: thread_get_state failed on Apple Silicon - faking zero debug registers
00dc:err:ole:com_get_class_object class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
0364:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
040c: thread_get_state failed on Apple Silicon - faking zero debug registers
016c: thread_get_state failed on Apple Silicon - faking zero debug registers
016c: thread_get_state failed on Apple Silicon - faking zero debug registers
0460:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0470: thread_get_state failed on Apple Silicon - faking zero debug registers
0478:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0478: thread_get_state failed on Apple Silicon - faking zero debug registers
0478: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0478: thread_get_state failed on Apple Silicon - faking zero debug registers
0484: thread_get_state failed on Apple Silicon - faking zero debug registers
048c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
048c: thread_get_state failed on Apple Silicon - faking zero debug registers
0494:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0494: thread_get_state failed on Apple Silicon - faking zero debug registers
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
04b8: thread_get_state failed on Apple Silicon - faking zero debug registers
04c0: thread_get_state failed on Apple Silicon - faking zero debug registers
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
04cc: thread_get_state failed on Apple Silicon - faking zero debug registers
04d8: thread_get_state failed on Apple Silicon - faking zero debug registers
04e4: thread_get_state failed on Apple Silicon - faking zero debug registers
04ec: thread_get_state failed on Apple Silicon - faking zero debug registers
04f4: thread_get_state failed on Apple Silicon - faking zero debug registers
0504: thread_get_state failed on Apple Silicon - faking zero debug registers
0504:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0560: thread_get_state failed on Apple Silicon - faking zero debug registers
0538:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
057c: thread_get_state failed on Apple Silicon - faking zero debug registers
0584: thread_get_state failed on Apple Silicon - faking zero debug registers
058c: thread_get_state failed on Apple Silicon - faking zero debug registers
0550:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
05b0: thread_get_state failed on Apple Silicon - faking zero debug registers
0558:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
05c0: thread_get_state failed on Apple Silicon - faking zero debug registers
05c4: thread_get_state failed on Apple Silicon - faking zero debug registers
0560:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
05e8: thread_get_state failed on Apple Silicon - faking zero debug registers
0624: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0660: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0668: thread_get_state failed on Apple Silicon - faking zero debug registers
0674: thread_get_state failed on Apple Silicon - faking zero debug registers
067c: thread_get_state failed on Apple Silicon - faking zero debug registers
0688:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0698: thread_get_state failed on Apple Silicon - faking zero debug registers
06b0: thread_get_state failed on Apple Silicon - faking zero debug registers
06b8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
06bc: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] GPU device:
		model: Apple M1
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003ef
		pipelineCacheUUID: DB8512A6-0E00-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
06c0: thread_get_state failed on Apple Silicon - faking zero debug registers
06d0: thread_get_state failed on Apple Silicon - faking zero debug registers
06e8: thread_get_state failed on Apple Silicon - faking zero debug registers
06f0: thread_get_state failed on Apple Silicon - faking zero debug registers
06fc: thread_get_state failed on Apple Silicon - faking zero debug registers
0700: thread_get_state failed on Apple Silicon - faking zero debug registers
0704: thread_get_state failed on Apple Silicon - faking zero debug registers
070c: thread_get_state failed on Apple Silicon - faking zero debug registers
071c:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
071c: thread_get_state failed on Apple Silicon - faking zero debug registers
04a8:err:wininet:HTTP_ParseDate unexpected date format L"Fri, 21 Jul 2023 10:00:00 UTC"
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
04a8: thread_get_state failed on Apple Silicon - faking zero debug registers
0724:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0748: thread_get_state failed on Apple Silicon - faking zero debug registers
074c: thread_get_state failed on Apple Silicon - faking zero debug registers
0724:err:ole:com_get_class_object no class object {2d3468c1-36a7-43b6-ac24-d3f02fd9607a} could be created for context 0x1
011c:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Jul 2023 06:00:00 UTC"
011c:err:wininet:HTTP_ParseDate unexpected date format L"Sat, 22 Jul 2023 06:00:00 UTC"
089c: thread_get_state failed on Apple Silicon - faking zero debug registers
08a4: thread_get_state failed on Apple Silicon - faking zero debug registers
08a8: thread_get_state failed on Apple Silicon - faking zero debug registers
08b0: thread_get_state failed on Apple Silicon - faking zero debug registers
016c: thread_get_state failed on Apple Silicon - faking zero debug registers
0910: thread_get_state failed on Apple Silicon - faking zero debug registers
Process exited with code 0
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by cirava** [comment] 2023-07-23 00:45
After some testing, I figured out this is actually an issue with how the game loads maps. I was able to go into the editor, and even play maps from the editor with great performance to boot, but as soon as I try to load a map in any way to regularly play it it doesn't work

**Comment by MarioPhD** [comment] 2023-07-23 22:01
I have the exact same problem, running on M1 macbook pro with Sonoma (MacOS 14), whisky 1.0.1

**Comment by IsaacMarovitz** [comment] 2023-07-24 13:11
Duplicate of #260

**Closed by IsaacMarovitz** 2023-07-24 13:11 UTC
Labels: bug, wine-bug
